# consul服务号端口
server:
  port: 80


spring:
  application:
    name: cloud-consumer-order
    ##### consul注册中心地址
  cloud:
    consul:
      discovery:
        #hostname 127.0.0.1
        service-name: ${spring.application.name}
      host: localhost
      port: 8500

